### ISSUE TITLE
Exception using mhd files

### ISSUE THREAD

**Issue by Maik-Lu** [embl-cba/elastixWrapper#17]
Greetings @tischi,
since recently I get an exception when I try loading .mhd files as moving or fixed image (I tried it with .tif stacks and it worked). The image opens but afterwards I get the following message:
>(Fiji Is Just) ImageJ 2.3.0/1.53q; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 202MB of 1288137MB (<1%)
>java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
>	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
>	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
>	at ij.IJ.runPlugIn(IJ.java)
>	at ij.Executer.runCommand(Executer.java:152)
>	at ij.Executer.run(Executer.java:70)
>	at java.lang.Thread.run(Thread.java:748)
>Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
>	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
>	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
>	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
>	... 5 more
>Caused by: java.lang.RuntimeException: Module threw exception
>	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
>	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
>	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
>	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>	... 1 more
>Caused by: java.lang.NullPointerException
>	at de.embl.cba.elastixwrapper.elastix.ElastixWrapper.stageImageAsMhd(ElastixWrapper.java:508)
>	at de.embl.cba.elastixwrapper.elastix.ElastixWrapper.stageImages(ElastixWrapper.java:384)
>	at de.embl.cba.elastixwrapper.elastix.ElastixWrapper.runElastix(ElastixWrapper.java:71)
>	at de.embl.cba.elastixwrapper.commands.ElastixCommand.runElastix(ElastixCommand.java:127)
>	at de.embl.cba.elastixwrapper.commands.ElastixCommand.run(ElastixCommand.java:116)
>	at org.scijava.command.CommandModule.run(CommandModule.java:196)
>	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
>	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
>	... 6 more

In addition I get in the Console:
> [INFO] Temporary directory is: ...
>[ERROR] The image could not be loaded: ...

Do you have a suggestion?
Thanks a lot,
Maik

**Comment by tischi** [comment]
Dear @Maik-Lu, 

Thank you very much for reporting this issue!

Could you please provide me with
- a screenshot of your settings 
- and the mdh file 

...such that I could test it here on my computer?
